### ISSUE TITLE
Numbered versions, distros types, contents modes 

### ISSUE THREAD

**Issue by Nycticorax** [openSUSE/openSUSE-docs-revamped#11]
There are three types of versioning we should keep in mind:

1. the actual version of the docs
2. _if we choose this structure_:  the actual distro it's meant for (TW vs Leap, for example)
3. _if we choose this structure_: whether we want to display the absolute maximial amount of details, versus if we want to display a "boiled down" version with just the details that matter, in which case the details would be adjusted for either: 
  3a. new users
  3b. the rest

There are other way to achieve the results in (2) and (3) without versioning. My point is just that this could be done thus.

**Comment by badarotti** [comment]
>     1. the actual version of the docs
It's best to use the versioning of openSUSE Leap (15.2, 15.3, etc.). We keep modifying the current docs until a new version of Leap is release then we branch the docs to the new version number. Just like we do with code. This will make it easily traceable for the doc reader as well as for developers to join us and document their stuff

>     2. _if we choose this structure_:  the actual distro it's meant for (TW vs Leap, for example)
Documentation wise I think there's little differences between Leap and Tumbleweed. So I think the documentation should be centered around Leap versioning  and if there are special consideration for TW then we mention it in article itself, maybe using special formatting. Making docs specifically for TW will be hard since it's a fast moving target. 

If there are obvious big differences, like updating the system for example, then separate articles in the same TOC tree should do the trick
 
>     3. _if we choose this structure_: whether we want to display the absolute maximial amount of details, versus if we want to display a "boiled down" version with just the details that matter, in which case the details would be adjusted for either:
>        3a. new users
>        3b. the rest
With the proposed structure, the absolute minimum sections are Pre-Install, Install & After Install and that is for all users not just new users. This is designed to get the user's system up and running as fast as possible. However In the install section there's an article 'Quick install guide for the experienced' for experienced Linux users who only needs pointers to openSUSE particularities. 

All the the detailed or advanced stuff should go in the 'Advanced topics section'

The documentation so far is for Desktop user. Following this same structure proposal we should have another set of docs for Server, MircoOS, Kubic, OBS, etc.

**Comment by Nycticorax** [comment]
I am all fine with the idea of using different docs versions for different distro numbers (15.2, 15.3,...). 

I think there are huge differences between Leap and TW in at least three respects: DE; kernel and day-to-day distro maintainance:
- DE: simply for the fact that TW ships with the latest Plasma and GNOME, debugging and troubleshooting DE-related stuff should make different assumptions and draw upon different resources to help the user. For example, TW correlates with more people using the wayland session, which has a different class of bugs in comparison with its Xorg counterpart.
- kernel: hardware support will be very, very different between Leap and TW, which means two kinds of troubleshooting.
- day-to-day distro maintainance: the TW "keep your distro up-to-date" is fundamentally different, especially if people use -- and we should recommend they do -- `tumbleweed-cli`

These differences should be reflected in the following parts of the docs (here I am using https://docs.google.com/document/d/1zERjqqQrWBAoM3B25BIQ4hvTFU_Y7S8L57bh-wb6ld4/ for reference):
- **Your openSUSE partitioning scheme** and **Picking a filesystem** => TW is best paired with Btrfs
- **The openSUSE trinity** => zypper and snapper in particular, which are used by `tumbleweed-cli`, should mention concepts and tricks specific to TW
- **GPU drivers** => as of now Nvidia requires much footwork to get a working with TW in the long run
- **Feeling at home** => TW correlates with more Wayland sessions meaning different kind of issues, 
- **Giving back to the community** => TW syncs up with different repositories and actioning Factory from TW is slightly different.

However I do agree with you that it would be an overkill to make a different _version_ of the docs because of the massive overlap in relevant technical information. So this leaves us with a question: How to present contents in way that:
- adapts to the users' expectation and needs (ie. if the user wants just the minimal amount of details to get the job done, he wants basically a list of steps; while if the user wants to understand more what's going on, a genuine text is more appropriate; so this would means 2 "modes" -- "just the steps" + "please explain more"
- reflects the differences between Leap and TW;

One solution I haven't mentioned so far that does not _might not_ (I don't know yet) using the versioning system for reflecting differences in contents could be like this:
1. For every single article, we determine:
  a. whether it benefits from Leap vs TW distinctions (or whether it is not applicable to one of the two distros)
  b. whether it benefits from the "just the steps" / "please explain more" distinction 
  When (a), we give the article an (a)-switch
  When (b), we give the article a (b)-switch.
2. For the whole documentation, we present the user with a global "switch all (a)-switches", and with a global "switch all (b)-switches".

**Comment by Nycticorax** [comment]
Closing this as I think we've make significant progress on the discussion with the present version. #17 will pick up the slate.
