### ISSUE TITLE
New page: Leap or Tumbleweed (distribution.md)

### ISSUE THREAD

**Issue by badarotti** [openSUSE/openSUSE-docs-revamped#9]
# New page: Leap or Tumbleweed
file: distribution.md
Live link: https://badarotti.github.io/openSUSE-docs-revamped/distribution/

This page is meant to be explain the differences between Leap and Tumbleweed. Make sure to see #8 first for context.

Please discuss the page here and if all goes well, I'll make a PR.
Thanks

---
# Leap or Tumbleweed

On the download site you'll find the two distribution choices: Leap and Tumbleweed. Both are openSUSE operating systems but they are targeted for different uses/users.

### openSUSE Leap

This is recommended distribution if you are a new user or you want a stable/production system. It is easy to use and will run with little maintenance or problems. 

During the lifetime of your install of openSUSE Leap version, you will receive security updates for all included packages as well as critical bug fixes.

A new minor release (15.0, 15.1, 15.2, etc.) is expected approximately every 12 months aligned with SUSE Linux Enterprise Service Pack (The commercial big brother of openSUSE).

A major release (15.0, 16.0, etc.) is expected approximately 36 to 48 months from the initial major release. This is also aligned with SUSE Linux Enterprise Releases

With Leap you have to explicitly instruct the operating system to upgrade to the latest minor or major releases. This will give you the opportunity to upgrade when you are ready and you have a proper tested back up.

### openSUSE Tumbleweed

This distribution is for the experienced Linux User. It is a rolling release that is constantly updated and always at the 'latest release'. Every update you perform will be a complete system upgrade. 

It receives security updates, bug fixes and new features (most often as new software versions) as soon as they are integrated and tested by the openSUSE community. Critical security updates for packages may also be provided in situations where new software versions may not yet address major security issues. 

Due to it's nature of being on the cutting edge, Tumbleweed updates tend to be frequent and big in size. If you have limited network connectivity Tumbleweed might be challenging to maintain.

Although the allure of having the latest software releases may be attractive to you, be sure to understand that using and maintaining Tumbleweed requires using the command line (for example regular system updates) and that sometimes upgrades cause problems that might frustrate you if you're not an experienced Linux user.

Tumbleweed officially supports more CPU architectures than Leap.

Don't let this detract you from using Tumbleweed in any way, If you are an experienced user with CLI knowledge and prefer the cutting edge of a rolling release, you will love Tumbleweed. It's well tested, stable and it's problems are minimal. 

## References 

- An openSUSE wiki page on [the lifetime cycles of Leap and Tumbleweed](https://en.opensuse.org/Lifetime).
- A ZDNet article covering [the differences between Leap and Tumbleweed](https://www.zdnet.com/article/side-by-side-opensuse-tumbleweed-and-leap/).

**Comment by surprized** [comment]
On Leap we should also make clear there are community repos for software in case someone wants to stay up to date on certain packages, and maybe say that they can usually be found at software.o-o.
I doubt the references part, because we may risk the ZDNet article getting deleted one day or being redirected, or who knows what. I'm fine with the wiki, but we should keep in mind that those can be easily modified by anyone, and so, it might lag behind the actual development, like lots of the wiki articles are right now.
Should we mention that TW, officially, supports more architectures than only x86_64, so for some users TW might be their only option.
Despite all of that, I find your page pretty good, it only talks about the necessary stuff to avoid making a choice between them complicated.

**Comment by badarotti** [comment]
@surprized Thanks for you input. Will add the architecture note to the Tumbleweed section.

Since this is aimed to be the official documentation, I hesitate to recommend repos other than the official ones. However you have a point, perhaps we can explain what those are in an article in the Post Install section along with the necessary caveats.

**Comment by Nycticorax** [comment]
Thanks for this, I think it's a strong start! I won't comment on anything but the text you've pasted above. Also I won't consider linguistic details it's not relevant as this point yet.

**openSUSELeap**
I would remove or tame:
* the idea that Leap is recommended for new users, because many different people can fall under the category of "new users" and still live a happy life with TW
* the idea that Leap is stable, because nowadays "stable" means everything and anything

Instead I would say that:
* Leap is recommended to people who don't want to worry too much about upgrades / updates, citing your reasons why this is so (just critical and bug fixes), and adding the example that Leap is mostly used in servers when updating often is not really adivseable (putting aside transactional updates OK)
* Leap is recommended to people who are OK with having softwares which are several months older than the builds or sources available at the devs' repos. I would stress that this counts toward stability (more time for testing) but also counts against comfort of use (less features or quality-life improvements). 
* By implication of the last point as it applies to the **kernel**, Leap is recommended to people who are OK with a kernel months if not years behind the latest build or source release, so that people which very new an exotic hardware should probably not go for Leap.

I would add:
* the notion that you can "upgrade" from Leap to TW itself, i.e. re-align repos and zypper dup settings to actually get TW just from Leap. Cannot go in the reverse direction though.

The rest of the text is fine.

**openSUSE TW**
Most of my comments follow from the above.

I would remove or tame:
* the idea that Leap is recommended to experienced users, because many different people can fall under the category of "new users" and still live a happy life with TW
* the idea that TW requires more CLI usage

Instead I would say that:
* TW is best paired with tumbleweed-cli (but just 1 command mostly) and snapper, which means that using TW properly requires a little bit of knowledge but more importantly understanding of the basic concepts behind the following concepts:
 * Brtfs snapshots
 * tumbleweed-cli snapshots (ie. clustered updates)
For these reasons I would thus say that TW is recommended to experienced users _and_ users OK with acquiring knowledge of these two concepts. Since it might involve trial-and-error, this means that users with critically important data and who don't have this knowledge should probably pass.

The rest of the text is fine.

**Comment by why-not-try-calmer** [comment]
Structure has changed. Contents moved onto "pick_an_image.md"
